name: Unit Test

on:
  pull_request:


jobs:
  unit_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Verify Python version
        run: |
          python --version
          python -c "import sys; print(f'Python version: {sys.version_info.major}.{sys.version_info.minor}')"
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: python -m pip install -e ".[dev]"
      - name: Run slice tests (test_slice.py) with coverage
        run: |
          TORCHSTORE_RDMA_ENABLED=0 \
          pytest tests/test_tensor_slice.py \
            --cov=. --cov-report=xml -vv -s
      - name: Run test_resharding_basic tests with coverage
        # TorchStore RDMA will not run on CPU-only machines
        # resharding tests runs for too long.
        # test_large_tensors.py can OOM.
        run: |
          TORCHSTORE_RDMA_ENABLED=0 \
          pytest tests/test_resharding_basic.py \
            --cov=. --cov-report=xml -vv -s
      - name: Run remaining tests with coverage
        # TorchStore RDMA will not run on CPU-only machines
        # resharding tests runs for too long.
        # test_large_tensors.py can OOM.
        run: |
          TORCHSTORE_RDMA_ENABLED=0 \
          pytest tests/ \
            --ignore=tests/test_resharding_basic.py \
            --ignore=tests/test_resharding_ext.py \
            --ignore=tests/test_tensor_slice.py \
            --ignore=tests/test_large_tensors.py \
            --cov=. --cov-report=xml --cov-append --durations=20 -vv -s
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
